version: "3"

services:
  norsk:
    container_name: norsk-server
    image: id3asnorsk/norsk:v0.0.322-main
    network_mode: host
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ${LOG_ROOT}:/var/log/norsk
    command: --license-file /mnt/license.json
    shm_size: '2gb'
    # cpuset: "0-15"
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    network_mode: host
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/06_audio_signal").main()'
  source_0:
    container_name: norsk-source_0
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        Running example 06_audio_signal
    depends_on:
      - example
  source_1:
    container_name: norsk-source_1
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        
    depends_on:
      - example
