version: "3"

services:
  norsk:
    image: id3asnorsk/norsk:v0.0.321-main
    network_mode: host
    volumes:
      - ./licensing/norsk_license.json:/mnt/license.json:ro
      - ./norskLogs:/var/log/norsk
    command: --license-file /mnt/license.json
    shm_size: '2gb'
    # cpuset: "0-15"
  example:
    build:
      context: ../examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    network_mode: host
    environment:
      - PUBLIC_IP=${PUBLIC_HOST}
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/simple/audio_signal").main()'
  source:
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        
    depends_on:
      - example
      