version: "3"

services:
  norsk:
    image: id3asnorsk/norsk:v0.0.321-main
    shm_size: '2gb'
    # cpuset: "0-15"
    volumes:
      - ./licensing/norsk_license.json:/mnt/license.json:ro
      - ./norskLogs:/var/log/norsk
    command: --license-file /mnt/license.json
    ports:
      - 5001:5001/tcp # For RTMP sources
      - 5001:5001/udp # For SRT sources
      - 6790:6790/tcp # GRPC interface
      - 6791:6791/tcp # Debugging endpoints, including the Media visualizer, logs, and docs
      - 8080:8080/tcp # Public endpoints for HLS/DASH and WebRTC players
  example_app:
    networks:
      default:
        aliases:
          - norsk
    environment:
      - NORSK_HOST=norsk
      - PUBLIC_IP=${PUBLIC_HOST}
    build:
      context: ../examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/simple/audio_signal").main()'
  source:
    image: datarhei/ffmpeg
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        
    depends_on:
      - example_app